### ISSUE TITLE
piwikUrl = colliding with Matomo Var

### ISSUE THREAD

**Issue by futureweb** [lippoliv/piwik-plugin-ajaxoptout#1]
Hey there,

just a little note - your var "piwikUrl" is colliding with Matomo Standard Script Sample for "duplicate the tracking data" --> https://developer.matomo.org/guides/tracking-javascript-guide

`_paq.push(['addTracker', piwikUrl = u+'piwik.php', websiteIdDuplicate]);`

bye from Austria
Andreas Schnederle-Wagner

**Comment by lippoliv** [comment]
@futureweb I [added it to my todo list](https://lw-scm.de/lipperts-web/piwik-ajax-opt-out/-/issues/6). Sorry for the late reply. I'll close the PRs and this issue once it's merged to master.

**Comment by lippoliv** [comment]
Took it over, thanks
