### ISSUE TITLE
Opt-Out per Page not per Piwik Server

### ISSUE THREAD

**Issue by futureweb** [lippoliv/piwik-plugin-ajaxoptout#4]
Hey there,
do you think it would be possible to make the Opt-Out Domain (or siteID) specific and not for all Pages tracked with one Piwik Server?
thx
Andreas Schnederle-Wagner

**Comment by lippoliv** [comment]
@futureweb The API just triggers the ignore cookie. How this interacts with Piwik / Matomo I do not modify.
