### ISSUE TITLE
doIgnore bug

### ISSUE THREAD

**Issue by Azd325** [lippoliv/piwik-plugin-ajaxoptout#6]
If I use doIgnore to set the ignore cookie and I used again the cookie value will be remove again. Is there away to check this beforehand in PHP? 
I think otherwise we could do this track and untrack with one api call?

**Comment by lippoliv** [comment]
@Azd325 thanks for reporting. I [tested multiple doIgnore calls](https://lw-scm.de/lipperts-web/piwik-ajax-opt-out/-/pipelines/9748/test_report) and it failed as you describe.

I added it [to my todo list](https://lw-scm.de/lipperts-web/piwik-ajax-opt-out/-/issues/8). I will fix it in the next update. Sorry that it took so long.

fyi @thibaultjunin

**Comment by lippoliv** [comment]
Is fixed. Thanks for the report :)
