### ISSUE TITLE
Web component for opt-out

### ISSUE THREAD

**Issue by peschee** [lippoliv/piwik-plugin-ajaxoptout#7]
Hi

I just published a web component that goes together with your Matomo plugin and handles the opt-out:

https://github.com/inventage/matomo-opt-out

Maybe you're interested in including it in your documentation.

**Comment by lippoliv** [comment]
@peschee Thank you very much. I just added it to my todo list https://lw-scm.de/lipperts-web/piwik-ajax-opt-out/-/issues/7. Once it's implemented, I'll close this issue.

**Comment by lippoliv** [comment]
I link your repo in the FAQs with the upcoming release. Thanks very much :)

If you like, feel free to create an PR for adding an HTML / JS example.

**Comment by peschee** [comment]
@lippoliv A simple instruction / example is listed in the README, I also have a running example here: https://glitch.com/~inventage-matomo-opt-out
